version: "3"
services:
  ping-one:
    build: .
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    networks:
      - netz-example-net-a
      - netz-example-net-b
  ping-two:
    build: .
    command: ping ping-one
    cap_add:
      - NET_ADMIN
    networks:
      - netz-example-net-a
  ping-three:
    build: .
    command: ping ping-one
    cap_add:
      - NET_ADMIN
    networks:
      - netz-example-net-b
  netz:
    build: ../../netz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/netz
networks:
  netz-example-net-a:
  netz-example-net-b:
