version: "3"
services:
  alice:
    build: .
    command: send bob
    cap_add:
      - NET_ADMIN
  bob:
    build: .
    command: receive
    cap_add:
      - NET_ADMIN
  netz:
    build: ../../netz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/netz
